Convert code base to TypeScript (fix #30)
julien-f/js-json-rpc-protocol pull request #31
Opened 2018-06-06 06:46 UTC by zixia

This PR had done the following tasks:

1. Convert all the .js files to .ts
1. Added the typing system to the source code
1. Added the TypeDef for JsonRpc Payload
1. Enable TypeScript for Jest
1. Replace `babel` to `tsc` for build scripts
1. Passed all unit tests 
1. Add `typings` entrance for enabling the TypeDef  of `json-rpc-protocol` NPM module in the package.json

BTW: I had tried many times trying to keep the change diff between rename operation, however, it seems that the Git system did not do this well, and [Linus said that was by design](https://stackoverflow.com/a/2314757/1123955) :-(

2018-06-09 20:22 UTC, julien-f requested changes

2018-06-09 20:22 UTC, julien-f commented on README.md
> +```shell
Unrelated changes, please remove.

Also this is not valid shell, due to the `>` indicating a prompt. :slightly_smiling_face:

2018-06-09 20:22 UTC, julien-f commented on package.json
> +  "main": "dist/index.js",
Why this change?

2018-06-09 20:22 UTC, julien-f commented on package.json
> +    "standard": "^11.0.1",
Is it still relevant?

2018-06-09 20:22 UTC, julien-f commented on package.json
> +    "build:babel": "cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/",
Is it still relevant?

2018-06-09 20:22 UTC, julien-f commented on package.json
> +    "dev:babel": "cross-env NODE_ENV=development babel --watch --source-maps --out-dir=dist/ src/",
Still relevant?

2018-06-09 20:22 UTC, julien-f commented on package.json
>      "posttest": "standard && dependency-check ./package.json",
Is it still relevant?

2018-06-09 20:22 UTC, julien-f commented on package.json
> +      "node"
I think you can just set `"ts"` here for the moment :slightly_smiling_face:

2018-06-09 20:22 UTC, julien-f commented on tslint.json
> +}
IMHO, instead of a manual custom config, it would be better to use something like:

```json
{
  "extends": [
    "tslint:recommended",
    "tslint-config-standard"
  ]
}
```

What do you think?

2018-06-09 20:22 UTC, julien-f commented on tsconfig.json
> +}
May I propose a minimal config based on `tsc --init`?

```json
{
  "compilerOptions": {
    "alwaysStrict": true,
    "declaration": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "sourceMap": true,
    "strict": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "target": "es5"
  }
}
```

2018-06-10 03:13 UTC, zixia commented on README.md
> +```shell
Ok.

However I'd like to suggest let's remove the `>` then add the _```shell_ in order to make `markdownlint`  happy.

2018-06-10 03:16 UTC, zixia commented on package.json
> +  "main": "dist/index.js",
In my projects, I'll always specify the exact file in package.json.

However, I believe `dist/` and `dist/index.js` should be the same.

Change reversed.

2018-06-10 03:19 UTC, zixia commented on package.json
> +    "standard": "^11.0.1",
I think it will not be relevant anymore.

We should use tslint with standard rules instead.

2018-06-10 03:19 UTC, zixia commented on package.json
> +    "build:babel": "cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/",
Not relevant anymore.

Removed.

2018-06-10 03:19 UTC, zixia commented on package.json
> +    "dev:babel": "cross-env NODE_ENV=development babel --watch --source-maps --out-dir=dist/ src/",
Not relevant anymore.

Removed.

2018-06-10 03:20 UTC, huan commented on package.json
>      "posttest": "standard && dependency-check ./package.json",
Assume you are asking for the `posttest` part:

I had removed the `standard` and keep the `dependency-check`.

2018-06-10 03:22 UTC, huan commented on package.json
> +      "node"
Yes, the `json` and `node` can be removed.

However, we have to keep the `js` at here, or `jest` will throw error.

2018-06-10 03:29 UTC, zixia commented on tslint.json
> +}
I think that would be clean and consistent, and we should do that.

I had just tried those two line rules, however, it seems it's not happy with our current code base and claimed too many errors.

So I'd like to suggest we keep the current tslint.json and fix it later.

2018-06-10 03:29 UTC, zixia commented on tsconfig.json
> +}
No problem, updated.

2018-06-10 03:32 UTC, zixia commented
I had modified the PR as you suggested.

2018-06-17 15:13 UTC, zixia commented
Tslint passed.

Two notes:

1. allow the interface not start with 'I' (see: <https://github.com/palantir/tslint/issues/3265>)
1. allow multiclass in one file for errors.ts

2018-06-17 15:33 UTC, merged

2018-06-17 15:33 UTC, julien-f commented
Thank you for your work :)

2018-06-17 15:49 UTC, zixia commented
You are welcome.

I had just file some new issues on the JsonRpcPeer, please have a look at them over there. :smiley: